_kanban/OpenWIS-Backlog-000195.md

kanban-updated-Jan-2017

---

_kanban/OpenWIS-Backlog-000195.md

Updated meeting agendas in kanban item

---

_minutes/2017-02-23-Agenda-OpenWIS-Annual-Meeting-2017-Toulouse.md
_minutes/2017-02-23-Agenda-OpenWIS-Steering-Committee-2017-Mar-Toulouse.md
_minutes/2017-02-23-Agenda-OpenWIS-Technical-Committee-2017-Mar-Toulouse.md

Added provisional agendas for TC/SC/AM to minutes page for further review/revision by association members.

Prep for toulouse - meeting agendas

---

_minutes/2017-02-23-Agenda-OpenWIS-Technical-Committee-2017-Mar-Toulouse.md
_sass/_base.scss

Includes a slight change to base css to remove spurious blank lines from
lists

Update to Agenda for March 2017 TC

---

_data/test.yml
_includes/comments.html
_layouts/default.html
_test/test.md
_test/test1.md
_test/test2.md
structure/governance.html

Found and fixed the errors on #116

fixed links for governance page

---

_minutes/2017-02-23-Agenda-OpenWIS-Technical-Committee-2017-Mar-Toulouse.md

Added links to demo instances

---

.gitignore
static/CLA/CLA-old-DO-NOT-DELETE/A-contributor-license-agreementv1.md
static/CLA/CLA-old-DO-NOT-DELETE/CLAformv1.md
static/CLA/CLAhistory.md

For use by organisational/multiple contributors

CLA process/form update

---

_data/excel2wis.yml
_includes/footer.html
_includes/header.html
_layouts/default.html
projects/excel2wis/index.html
projects/index.html

I have made updates to the website including the inclusion of the excel2wis page, and modifications to the project page and the drop-down menus.

Gh pages nws

---

_minutes/2017-03-22-OpenWIS-Steering-Committee.md

Minutes of SC meeting in Toulouse on 22/23 March 2017 added to website

Update Toulouse 2017 SC

---

_minutes/2017-03-23-OpenWIS-Annual-Meeting.md

Minor corrections to Board minutes.

BM cors 2017 05 11

---

static/CLA/CLAform.md

Added table for Contributor details

Minor-CLA-form-update-1

---

_minutes/2017-06-29-OpenWIS-Steering-Committee-2017-Jun.md

2017-June-SC-1

---

_minutes/2017-08-10-OpenWIS-Technical-Committee-2017-Aug.md

Tc 2017 08 1

---

_minutes/2017-09-28-OpenWIS-Technical-Committee-2017-Sep.md

Added TC minutes for Sep 2017

---

_minutes/2017-10-09-OpenWIS-Steering-Committee-2017-Oct.md

SC-2017-10-09-1

---

_metrics/OpenWIS-Metrics-A1.md

Removed metric A1.2
Updated metric A1.1

Updated Goal A1 for Assoc

---

_minutes/2018-05-31-OpenWIS-Board-Meeting-2018-May.md

BM mins May 2018

---

_minutes/2018-05-30-OpenWIS-Steering-Committee-2018-May.md

SC minutes May 2018

---

_minutes/2018-05-29-OpenWIS-Technical-Committee-2018-May.md
_minutes/2018-05-30-OpenWIS-Steering-Committee-2018-May.md

1. Added 2018 May TC
2. Minor correction to 2018 May SC mins

TC minutes 2018-05

---

_includes/header.html

Update Projects dropdown

---

_minutes/board/2019-05-23-OpenWIS-Board-Meeting-2019-May.md
_minutes/steering/2019-05-22-OpenWIS-Steering-Committee-2019-May.md
_minutes/technical/2019-05-21-OpenWIS-Technical-Committee-2019-May.md

More formatting changes to fix markdown

May 19 Minutes  - formatting chnages to TC SC and Board

---

_minutes/steering/2020-12-07-OpenWIS-Steering-Committee-2020-Sep.md

Reverts OpenWIS/openwis-documentation#614

Revert "Update 2020-12-07-OpenWIS-Steering-Committee-2020-Sep.md"

---

_minutes/steering/2021-03-24-OpenWIS-Steering-Committee-2021-Mar.md

Publish SC minutes of March 2021

SC Minutes of March 2021

---

_minutes/2021-03-24-OpenWIS-Steering-Committee-2021-Mar.md

Publish minutes for 24 March 2021 SC minutes

Publish SC minutes for March 2021

---

_minutes/board/2021-05-26-OpenWIS-Board-Meeting-2021-May.md

Publish May 2021 Board minutes

---

_minutes/steering/2021-05-17-OpenWIS-Steering-Committee-2021-May.md

Publish May 2021 SC Minutes

---

_minutes/technical/2021-05-11 OpenWIS-Technical-Committee-2021-May.md

Publish TC Annual Meeting May 2021 minutes

Publish TC Annual Meeting May 2021 minutes
